#include "txcoreconfig.h"
#include <sys/types.h>
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include "texint.h"

/* List of errno names: */

const TXCODEDESC        TXerrnoNames[] =
{
  /* no EOK: make err 0=Ok across platforms for consistent tests */
  { 0, "Ok" },
#ifdef EPERM
  TXCODEDESC_ITEM(EPERM),
#endif
#ifdef ENOENT
  TXCODEDESC_ITEM(ENOENT),
#endif
#ifdef ESRCH
  TXCODEDESC_ITEM(ESRCH),
#endif
#ifdef EINTR
  TXCODEDESC_ITEM(EINTR),
#endif
#ifdef EIO
  TXCODEDESC_ITEM(EIO),
#endif
#ifdef ENXIO
  TXCODEDESC_ITEM(ENXIO),
#endif
#ifdef E2BIG
  TXCODEDESC_ITEM(E2BIG),
#endif
#ifdef ENOEXEC
  TXCODEDESC_ITEM(ENOEXEC),
#endif
#ifdef EBADF
  TXCODEDESC_ITEM(EBADF),
#endif
#ifdef ECHILD
  TXCODEDESC_ITEM(ECHILD),
#endif
#ifdef EAGAIN
  TXCODEDESC_ITEM(EAGAIN),
#endif
#ifdef ENOMEM
  TXCODEDESC_ITEM(ENOMEM),
#endif
#ifdef EACCES
  TXCODEDESC_ITEM(EACCES),
#endif
#ifdef EFAULT
  TXCODEDESC_ITEM(EFAULT),
#endif
#ifdef ENOTBLK
  TXCODEDESC_ITEM(ENOTBLK),
#endif
#ifdef EBUSY
  TXCODEDESC_ITEM(EBUSY),
#endif
#ifdef EEXIST
  TXCODEDESC_ITEM(EEXIST),
#endif
#ifdef EXDEV
  TXCODEDESC_ITEM(EXDEV),
#endif
#ifdef ENODEV
  TXCODEDESC_ITEM(ENODEV),
#endif
#ifdef ENOTDIR
  TXCODEDESC_ITEM(ENOTDIR),
#endif
#ifdef EISDIR
  TXCODEDESC_ITEM(EISDIR),
#endif
#ifdef EINVAL
  TXCODEDESC_ITEM(EINVAL),
#endif
#ifdef ENFILE
  TXCODEDESC_ITEM(ENFILE),
#endif
#ifdef EMFILE
  TXCODEDESC_ITEM(EMFILE),
#endif
#ifdef ENOTTY
  TXCODEDESC_ITEM(ENOTTY),
#endif
#ifdef ETXTBSY
  TXCODEDESC_ITEM(ETXTBSY),
#endif
#ifdef EFBIG
  TXCODEDESC_ITEM(EFBIG),
#endif
#ifdef ENOSPC
  TXCODEDESC_ITEM(ENOSPC),
#endif
#ifdef ESPIPE
  TXCODEDESC_ITEM(ESPIPE),
#endif
#ifdef EROFS
  TXCODEDESC_ITEM(EROFS),
#endif
#ifdef EMLINK
  TXCODEDESC_ITEM(EMLINK),
#endif
#ifdef EPIPE
  TXCODEDESC_ITEM(EPIPE),
#endif
#ifdef EDOM
  TXCODEDESC_ITEM(EDOM),
#endif
#ifdef ERANGE
  TXCODEDESC_ITEM(ERANGE),
#endif
#ifdef EDEADLK
  TXCODEDESC_ITEM(EDEADLK),
#endif
#ifdef ENAMETOOLONG
  TXCODEDESC_ITEM(ENAMETOOLONG),
#endif
#ifdef ENOLCK
  TXCODEDESC_ITEM(ENOLCK),
#endif
#ifdef ENOSYS
  TXCODEDESC_ITEM(ENOSYS),
#endif
#ifdef ENOTEMPTY
  TXCODEDESC_ITEM(ENOTEMPTY),
#endif
#ifdef ELOOP
  TXCODEDESC_ITEM(ELOOP),
#endif
#ifdef EWOULDBLOCK
  TXCODEDESC_ITEM(EWOULDBLOCK),
#endif
#ifdef ENOMSG
  TXCODEDESC_ITEM(ENOMSG),
#endif
#ifdef EIDRM
  TXCODEDESC_ITEM(EIDRM),
#endif
#ifdef ECHRNG
  TXCODEDESC_ITEM(ECHRNG),
#endif
#ifdef EL2NSYNC
  TXCODEDESC_ITEM(EL2NSYNC),
#endif
#ifdef EL3HLT
  TXCODEDESC_ITEM(EL3HLT),
#endif
#ifdef EL3RST
  TXCODEDESC_ITEM(EL3RST),
#endif
#ifdef ELNRNG
  TXCODEDESC_ITEM(ELNRNG),
#endif
#ifdef EUNATCH
  TXCODEDESC_ITEM(EUNATCH),
#endif
#ifdef ENOCSI
  TXCODEDESC_ITEM(ENOCSI),
#endif
#ifdef EL2HLT
  TXCODEDESC_ITEM(EL2HLT),
#endif
#ifdef EBADE
  TXCODEDESC_ITEM(EBADE),
#endif
#ifdef EBADR
  TXCODEDESC_ITEM(EBADR),
#endif
#ifdef EXFULL
  TXCODEDESC_ITEM(EXFULL),
#endif
#ifdef ENOANO
  TXCODEDESC_ITEM(ENOANO),
#endif
#ifdef EBADRQC
  TXCODEDESC_ITEM(EBADRQC),
#endif
#ifdef EBADSLT
  TXCODEDESC_ITEM(EBADSLT),
#endif
#ifdef EDEADLOCK
  TXCODEDESC_ITEM(EDEADLOCK),
#endif
#ifdef EBFONT
  TXCODEDESC_ITEM(EBFONT),
#endif
#ifdef ENOSTR
  TXCODEDESC_ITEM(ENOSTR),
#endif
#ifdef ENODATA
  TXCODEDESC_ITEM(ENODATA),
#endif
#ifdef ETIME
  TXCODEDESC_ITEM(ETIME),
#endif
#ifdef ENOSR
  TXCODEDESC_ITEM(ENOSR),
#endif
#ifdef ENONET
  TXCODEDESC_ITEM(ENONET),
#endif
#ifdef ENOPKG
  TXCODEDESC_ITEM(ENOPKG),
#endif
#ifdef EREMOTE
  TXCODEDESC_ITEM(EREMOTE),
#endif
#ifdef ENOLINK
  TXCODEDESC_ITEM(ENOLINK),
#endif
#ifdef EADV
  TXCODEDESC_ITEM(EADV),
#endif
#ifdef ESRMNT
  TXCODEDESC_ITEM(ESRMNT),
#endif
#ifdef ECOMM
  TXCODEDESC_ITEM(ECOMM),
#endif
#ifdef EPROTO
  TXCODEDESC_ITEM(EPROTO),
#endif
#ifdef EMULTIHOP
  TXCODEDESC_ITEM(EMULTIHOP),
#endif
#ifdef EDOTDOT
  TXCODEDESC_ITEM(EDOTDOT),
#endif
#ifdef EBADMSG
  TXCODEDESC_ITEM(EBADMSG),
#endif
#ifdef EOVERFLOW
  TXCODEDESC_ITEM(EOVERFLOW),
#endif
#ifdef ENOTUNIQ
  TXCODEDESC_ITEM(ENOTUNIQ),
#endif
#ifdef EBADFD
  TXCODEDESC_ITEM(EBADFD),
#endif
#ifdef EREMCHG
  TXCODEDESC_ITEM(EREMCHG),
#endif
#ifdef ELIBACC
  TXCODEDESC_ITEM(ELIBACC),
#endif
#ifdef ELIBBAD
  TXCODEDESC_ITEM(ELIBBAD),
#endif
#ifdef ELIBSCN
  TXCODEDESC_ITEM(ELIBSCN),
#endif
#ifdef ELIBMAX
  TXCODEDESC_ITEM(ELIBMAX),
#endif
#ifdef ELIBEXEC
  TXCODEDESC_ITEM(ELIBEXEC),
#endif
#ifdef EILSEQ
  TXCODEDESC_ITEM(EILSEQ),
#endif
#ifdef ERESTART
  TXCODEDESC_ITEM(ERESTART),
#endif
#ifdef ESTRPIPE
  TXCODEDESC_ITEM(ESTRPIPE),
#endif
#ifdef EUSERS
  TXCODEDESC_ITEM(EUSERS),
#endif
#ifdef ENOTSOCK
  TXCODEDESC_ITEM(ENOTSOCK),
#endif
#ifdef EDESTADDRREQ
  TXCODEDESC_ITEM(EDESTADDRREQ),
#endif
#ifdef EMSGSIZE
  TXCODEDESC_ITEM(EMSGSIZE),
#endif
#ifdef EPROTOTYPE
  TXCODEDESC_ITEM(EPROTOTYPE),
#endif
#ifdef ENOPROTOOPT
  TXCODEDESC_ITEM(ENOPROTOOPT),
#endif
#ifdef EPROTONOSUPPORT
  TXCODEDESC_ITEM(EPROTONOSUPPORT),
#endif
#ifdef ESOCKTNOSUPPORT
  TXCODEDESC_ITEM(ESOCKTNOSUPPORT),
#endif
#ifdef EOPNOTSUPP
  TXCODEDESC_ITEM(EOPNOTSUPP),
#endif
#ifdef EPFNOSUPPORT
  TXCODEDESC_ITEM(EPFNOSUPPORT),
#endif
#ifdef EAFNOSUPPORT
  TXCODEDESC_ITEM(EAFNOSUPPORT),
#endif
#ifdef EADDRINUSE
  TXCODEDESC_ITEM(EADDRINUSE),
#endif
#ifdef EADDRNOTAVAIL
  TXCODEDESC_ITEM(EADDRNOTAVAIL),
#endif
#ifdef ENETDOWN
  TXCODEDESC_ITEM(ENETDOWN),
#endif
#ifdef ENETUNREACH
  TXCODEDESC_ITEM(ENETUNREACH),
#endif
#ifdef ENETRESET
  TXCODEDESC_ITEM(ENETRESET),
#endif
#ifdef ECONNABORTED
  TXCODEDESC_ITEM(ECONNABORTED),
#endif
#ifdef ECONNRESET
  TXCODEDESC_ITEM(ECONNRESET),
#endif
#ifdef ENOBUFS
  TXCODEDESC_ITEM(ENOBUFS),
#endif
#ifdef EISCONN
  TXCODEDESC_ITEM(EISCONN),
#endif
#ifdef ENOTCONN
  TXCODEDESC_ITEM(ENOTCONN),
#endif
#ifdef ESHUTDOWN
  TXCODEDESC_ITEM(ESHUTDOWN),
#endif
#ifdef ETOOMANYREFS
  TXCODEDESC_ITEM(ETOOMANYREFS),
#endif
#ifdef ETIMEDOUT
  TXCODEDESC_ITEM(ETIMEDOUT),
#endif
#ifdef ECONNREFUSED
  TXCODEDESC_ITEM(ECONNREFUSED),
#endif
#ifdef EHOSTDOWN
  TXCODEDESC_ITEM(EHOSTDOWN),
#endif
#ifdef EHOSTUNREACH
  TXCODEDESC_ITEM(EHOSTUNREACH),
#endif
#ifdef EALREADY
  TXCODEDESC_ITEM(EALREADY),
#endif
#ifdef EINPROGRESS
  TXCODEDESC_ITEM(EINPROGRESS),
#endif
#ifdef ESTALE
  TXCODEDESC_ITEM(ESTALE),
#endif
#ifdef EUCLEAN
  TXCODEDESC_ITEM(EUCLEAN),
#endif
#ifdef ENOTNAM
  TXCODEDESC_ITEM(ENOTNAM),
#endif
#ifdef ENAVAIL
  TXCODEDESC_ITEM(ENAVAIL),
#endif
#ifdef EISNAM
  TXCODEDESC_ITEM(EISNAM),
#endif
#ifdef EREMOTEIO
  TXCODEDESC_ITEM(EREMOTEIO),
#endif
#ifdef EDQUOT
  TXCODEDESC_ITEM(EDQUOT),
#endif
#ifdef ENOMEDIUM
  TXCODEDESC_ITEM(ENOMEDIUM),
#endif
#ifdef EMEDIUMTYPE
  TXCODEDESC_ITEM(EMEDIUMTYPE),
#endif
#ifdef ECANCELED
  TXCODEDESC_ITEM(ECANCELED),
#endif
#ifdef ENOKEY
  TXCODEDESC_ITEM(ENOKEY),
#endif
#ifdef EKEYEXPIRED
  TXCODEDESC_ITEM(EKEYEXPIRED),
#endif
#ifdef EKEYREVOKED
  TXCODEDESC_ITEM(EKEYREVOKED),
#endif
#ifdef EKEYREJECTED
  TXCODEDESC_ITEM(EKEYREJECTED),
#endif
#ifdef EOWNERDEAD
  TXCODEDESC_ITEM(EOWNERDEAD),
#endif
#ifdef ENOTRECOVERABLE
  TXCODEDESC_ITEM(ENOTRECOVERABLE),
#endif
#ifdef ERFKILL
  TXCODEDESC_ITEM(ERFKILL),
#endif
#ifdef EHWPOISON
  TXCODEDESC_ITEM(EHWPOISON),
#endif
  {0, NULL }
};
