/* Copyright (C) 2026 Aaron Flin - All Rights Reserved
 * MIT license -- https://opensource.org/licenses/MIT
 *
 * rampart-textencoding.c
 *
 * Replace duktape's permissive utf-8-only TextEncoder/TextDecoder
 * with WHATWG-spec-compatible globals.  Routed through the
 * rampart-buffer.c encoders, so the supported set is what Buffer
 * supports: utf-8, utf-16le, utf-16be (via byte-swap), iso-8859-1
 * (latin1, binary), us-ascii.  Unknown labels throw RangeError.
 *
 * Wired into register.c via duk_rp_textencoding_init() AFTER
 * duk_rp_buffer_init() runs (we depend on Buffer.toString being
 * the extended version).
 */

#include "duktape.h"
#include "rampart.h"
#include "rampart-textencoding.h"

static const char *_textencoding_js =
"function() {\n"
"  'use strict';\n"
"\n"
"  /* WHATWG -> canonical encoding name.  The list below is the\n"
"     subset rampart's Buffer can decode correctly. */\n"
"  function _canonical(label) {\n"
"    if (label === undefined) return 'utf-8';\n"
"    var n = String(label).trim().toLowerCase();\n"
"    if (/^(utf-?8|unicode-1-1-utf-8|unicode11utf8|unicode20utf8)$/.test(n)) return 'utf-8';\n"
"    if (/^(utf-?16|utf-?16le|csunicode|iso-10646-ucs-2|ucs-2|unicode|unicodefeff)$/.test(n)) return 'utf-16le';\n"
"    if (/^(utf-?16be|unicodefffe)$/.test(n)) return 'utf-16be';\n"
"    if (/^(iso-?8859-?1|latin1|binary|csisolatin1|iso-ir-100|iso_8859-1|l1|cp819|ibm819)$/.test(n)) return 'iso-8859-1';\n"
"    if (/^(us-?ascii|ascii|ansi_x3\\.4-1968|cp367|csascii|iso-ir-6|iso646-us|ibm367)$/.test(n)) return 'us-ascii';\n"
"    return null;   /* unsupported */\n"
"  }\n"
"\n"
"  /* Normalize input into a Buffer view we can pass through the\n"
"     Buffer toString helpers.  Accepts Buffer, Uint8Array, ArrayBuffer,\n"
"     any TypedArray view, or undefined (treated as empty). */\n"
"  function _toBuffer(input) {\n"
"    if (input === undefined || input === null) return Buffer.alloc(0);\n"
"    if (Buffer.isBuffer(input)) return input;\n"
"    if (input instanceof ArrayBuffer) return Buffer.from(new Uint8Array(input));\n"
"    if (input.buffer instanceof ArrayBuffer && typeof input.byteOffset === 'number')\n"
"      return Buffer.from(input.buffer, input.byteOffset, input.byteLength);\n"
"    if (typeof input.length === 'number') return Buffer.from(input);\n"
"    var e = new TypeError('Expected input to be a BufferSource');\n"
"    e.code = 'ERR_INVALID_ARG_TYPE'; throw e;\n"
"  }\n"
"\n"
"  /* WHATWG-style UTF-8 decoder that emits U+FFFD for invalid\n"
"     sequences.  Replaces Buffer.toString('utf8') for the\n"
"     fatal:false path, which doesn't do replacement.  Supplementary\n"
"     codepoints (>U+FFFF) are emitted as JS surrogate pairs (the\n"
"     duktape string representation for those codepoints). */\n"
"  function _utf8DecodeReplace(buf) {\n"
"    var out = '';\n"
"    var len = buf.length;\n"
"    var i = 0;\n"
"    while (i < len) {\n"
"      var b = buf[i];\n"
"      if (b < 0x80) { out += String.fromCharCode(b); i++; continue; }\n"
"      var need, loMin, hiMax, cp;\n"
"      if ((b & 0xE0) === 0xC0 && b >= 0xC2)      { need = 1; loMin = 0x80; hiMax = 0xBF; cp = b & 0x1F; }\n"
"      else if ((b & 0xF0) === 0xE0)              { need = 2; loMin = (b === 0xE0) ? 0xA0 : 0x80; hiMax = (b === 0xED) ? 0x9F : 0xBF; cp = b & 0x0F; }\n"
"      else if ((b & 0xF8) === 0xF0 && b <= 0xF4) { need = 3; loMin = (b === 0xF0) ? 0x90 : 0x80; hiMax = (b === 0xF4) ? 0x8F : 0xBF; cp = b & 0x07; }\n"
"      else { out += '\\uFFFD'; i++; continue; }   /* invalid lead */\n"
"      var ok = true;\n"
"      for (var k = 0; k < need; k++) {\n"
"        if (i + 1 + k >= len) { ok = false; break; }\n"
"        var cb = buf[i + 1 + k];\n"
"        var lo = (k === 0) ? loMin : 0x80;\n"
"        var hi = (k === 0) ? hiMax : 0xBF;\n"
"        if (cb < lo || cb > hi) { ok = false; break; }\n"
"        cp = (cp << 6) | (cb & 0x3F);\n"
"      }\n"
"      if (!ok) { out += '\\uFFFD'; i++; continue; }   /* per spec: advance 1, restart */\n"
"      if (cp < 0x10000) {\n"
"        out += String.fromCharCode(cp);\n"
"      } else {\n"
"        cp -= 0x10000;\n"
"        out += String.fromCharCode(0xD800 + (cp >> 10), 0xDC00 + (cp & 0x3FF));\n"
"      }\n"
"      i += need + 1;\n"
"    }\n"
"    return out;\n"
"  }\n"
"\n"
"  /* Strict utf-8 validation.  Returns true if every byte sequence is\n"
"     a well-formed utf-8 codepoint; false otherwise.  Used for the\n"
"     fatal:true contract on utf-8. */\n"
"  function _validUtf8(buf) {\n"
"    var i = 0, len = buf.length;\n"
"    while (i < len) {\n"
"      var b = buf[i];\n"
"      var need;\n"
"      if (b < 0x80) { i++; continue; }\n"
"      if ((b & 0xE0) === 0xC0) { need = 1; if (b < 0xC2) return false; }\n"
"      else if ((b & 0xF0) === 0xE0) { need = 2; }\n"
"      else if ((b & 0xF8) === 0xF0) { need = 3; if (b > 0xF4) return false; }\n"
"      else return false;\n"
"      if (i + need >= len) return false;\n"
"      for (var k = 1; k <= need; k++) {\n"
"        if ((buf[i+k] & 0xC0) !== 0x80) return false;\n"
"      }\n"
"      i += need + 1;\n"
"    }\n"
"    return true;\n"
"  }\n"
"\n"
"  /* ----- TextDecoder ----- */\n"
"\n"
"  function TextDecoder(label, options) {\n"
"    if (!(this instanceof TextDecoder)) return new TextDecoder(label, options);\n"
"    var canonical = _canonical(label);\n"
"    if (canonical === null) {\n"
"      var e = new RangeError(\"The encoding label provided ('\" + label + \"') is invalid.\");\n"
"      e.code = 'ERR_ENCODING_NOT_SUPPORTED';\n"
"      throw e;\n"
"    }\n"
"    options = options || {};\n"
"    /* Spec exposes encoding/fatal/ignoreBOM as read-only own props. */\n"
"    Object.defineProperty(this, 'encoding',  {value: canonical,             enumerable: true});\n"
"    Object.defineProperty(this, 'fatal',     {value: !!options.fatal,       enumerable: true});\n"
"    Object.defineProperty(this, 'ignoreBOM', {value: !!options.ignoreBOM,   enumerable: true});\n"
"  }\n"
"\n"
"  /* Strip a leading BOM if present in the matching encoding.  Per the\n"
"     spec, BOM stripping is automatic unless ignoreBOM:true was set. */\n"
"  function _stripBom(buf, enc) {\n"
"    if (enc === 'utf-8' && buf.length >= 3\n"
"        && buf[0] === 0xEF && buf[1] === 0xBB && buf[2] === 0xBF)\n"
"      return buf.slice(3);\n"
"    if (enc === 'utf-16le' && buf.length >= 2\n"
"        && buf[0] === 0xFF && buf[1] === 0xFE)\n"
"      return buf.slice(2);\n"
"    if (enc === 'utf-16be' && buf.length >= 2\n"
"        && buf[0] === 0xFE && buf[1] === 0xFF)\n"
"      return buf.slice(2);\n"
"    return buf;\n"
"  }\n"
"\n"
"  /* Find boundary in `buf` where the trailing bytes start an incomplete\n"
"     UTF-8 multi-byte sequence.  Returns the index of the first incomplete\n"
"     byte (i.e. buf.length if everything is complete). */\n"
"  function _utf8ResidualBoundary(buf) {\n"
"    var n = buf.length;\n"
"    for (var i = n - 1; i >= Math.max(0, n - 3); i--) {\n"
"      var b = buf[i];\n"
"      if (b < 0x80) return n;        /* ASCII boundary, all complete */\n"
"      if (b < 0xC0) continue;        /* continuation byte, keep walking */\n"
"      var need = (b < 0xE0) ? 2 : (b < 0xF0) ? 3 : 4;\n"
"      if (n - i >= need) return n;   /* full sequence present */\n"
"      return i;                      /* incomplete — residual starts here */\n"
"    }\n"
"    return n;\n"
"  }\n"
"  TextDecoder.prototype.decode = function(input, opts) {\n"
"    var buf = _toBuffer(input);\n"
"    var stream = !!(opts && opts.stream);\n"
"    /* Prepend any residual bytes saved from a prior streaming call. */\n"
"    if (this._residual) {\n"
"      buf = Buffer.concat([this._residual, buf]);\n"
"      this._residual = null;\n"
"    }\n"
"    /* BOM is checked once, on the first byte of the stream. */\n"
"    if (!this.ignoreBOM && !this._bomChecked) {\n"
"      buf = _stripBom(buf, this.encoding);\n"
"      this._bomChecked = true;\n"
"    }\n"
"    /* In streaming mode, hold back trailing bytes that start an incomplete\n"
"       multi-byte sequence so they can be combined with the next chunk\n"
"       (matches WHATWG TextDecoder stream:true semantics — required for\n"
"       TextDecoderStream of UTF-8 across chunk boundaries). */\n"
"    if (stream) {\n"
"      if (this.encoding === 'utf-8') {\n"
"        var bound = _utf8ResidualBoundary(buf);\n"
"        if (bound < buf.length) {\n"
"          this._residual = buf.slice(bound);\n"
"          buf = buf.slice(0, bound);\n"
"        }\n"
"      } else if (this.encoding === 'utf-16le' || this.encoding === 'utf-16be') {\n"
"        /* Odd byte count → save trailing byte for next chunk. */\n"
"        if (buf.length & 1) {\n"
"          this._residual = buf.slice(buf.length - 1);\n"
"          buf = buf.slice(0, buf.length - 1);\n"
"        }\n"
"      }\n"
"      /* iso-8859-1 / us-ascii are byte-per-codepoint — no residual needed. */\n"
"    } else {\n"
"      /* Final call — reset BOM/residual state for any subsequent stream. */\n"
"      this._bomChecked = false;\n"
"    }\n"
"\n"
"    var enc = this.encoding;\n"
"    if (enc === 'utf-8') {\n"
"      if (this.fatal && !_validUtf8(buf)) {\n"
"        var e = new TypeError('The encoded data was not valid for encoding utf-8');\n"
"        e.code = 'ERR_ENCODING_INVALID_ENCODED_DATA'; throw e;\n"
"      }\n"
"      /* WHATWG spec mandates U+FFFD replacement for invalid sequences\n"
"         in non-fatal mode.  Buffer.toString('utf8') passes invalid\n"
"         bytes through as Latin-1, so we use a JS decoder. */\n"
"      return _utf8DecodeReplace(buf);\n"
"    }\n"
"    if (enc === 'utf-16le') {\n"
"      /* utf-16le has no per-byte error to detect; buffer length must\n"
"         be even, but the spec just discards the trailing odd byte. */\n"
"      return buf.toString('utf16le');\n"
"    }\n"
"    if (enc === 'utf-16be') {\n"
"      /* Byte-swap pairs then reuse utf-16le decoder. */\n"
"      var pairs = buf.length & ~1;   /* round down to even */\n"
"      var swapped = Buffer.alloc(pairs);\n"
"      for (var i = 0; i < pairs; i += 2) {\n"
"        swapped[i]     = buf[i+1];\n"
"        swapped[i + 1] = buf[i];\n"
"      }\n"
"      return swapped.toString('utf16le');\n"
"    }\n"
"    if (enc === 'iso-8859-1') {\n"
"      return buf.toString('latin1');\n"
"    }\n"
"    if (enc === 'us-ascii') {\n"
"      if (this.fatal) {\n"
"        for (var j = 0; j < buf.length; j++) {\n"
"          if (buf[j] > 0x7F) {\n"
"            var e2 = new TypeError('The encoded data was not valid for encoding us-ascii');\n"
"            e2.code = 'ERR_ENCODING_INVALID_ENCODED_DATA'; throw e2;\n"
"          }\n"
"        }\n"
"      }\n"
"      /* Buffer.toString('ascii') masks the high bit (0x80 → 0x00 etc.)\n"
"         per node's behavior. */\n"
"      return buf.toString('ascii');\n"
"    }\n"
"    return '';  /* unreachable -- _canonical filtered */\n"
"  };\n"
"\n"
"  /* ----- TextEncoder ----- */\n"
"\n"
"  /* We keep duktape's existing TextEncoder constructor (utf-8 only,\n"
"     per spec) but ensure encodeInto is present.  duktape's encode()\n"
"     returns a Uint8Array of utf-8 bytes.\n"
"\n"
"     The original encode() is duktape's native impl; we don't replace\n"
"     it.  We only attach encodeInto. */\n"
"  function _utf8ByteLenOfCodepoint(cp) {\n"
"    if (cp < 0x80) return 1;\n"
"    if (cp < 0x800) return 2;\n"
"    return 3;     /* BMP cap; surrogate pair handled separately */\n"
"  }\n"
"\n"
"  if (typeof TextEncoder !== 'undefined' &&\n"
"      typeof TextEncoder.prototype.encodeInto !== 'function') {\n"
"    TextEncoder.prototype.encodeInto = function(source, dest) {\n"
"      if (typeof source !== 'string') source = String(source);\n"
"      if (!dest || typeof dest.length !== 'number')\n"
"        throw new TypeError('dest must be a Uint8Array');\n"
"\n"
"      var bytes = this.encode(source);   /* duktape native */\n"
"      var n = Math.min(bytes.length, dest.length);\n"
"      for (var i = 0; i < n; i++) dest[i] = bytes[i];\n"
"\n"
"      /* If dest was big enough, we consumed every code unit. */\n"
"      if (n === bytes.length) return {read: source.length, written: n};\n"
"\n"
"      /* Truncated.  Walk source code-unit-by-code-unit, summing the\n"
"         utf-8 byte cost of each codepoint until we'd overflow `n`. */\n"
"      var encoded = 0, ci = 0;\n"
"      while (ci < source.length) {\n"
"        var cp = source.charCodeAt(ci);\n"
"        var cost;\n"
"        if (cp >= 0xD800 && cp <= 0xDBFF && ci + 1 < source.length) {\n"
"          var lo = source.charCodeAt(ci + 1);\n"
"          if (lo >= 0xDC00 && lo <= 0xDFFF) {\n"
"            cost = 4;\n"
"            if (encoded + cost > n) break;\n"
"            encoded += cost; ci += 2; continue;\n"
"          }\n"
"        }\n"
"        cost = _utf8ByteLenOfCodepoint(cp);\n"
"        if (encoded + cost > n) break;\n"
"        encoded += cost; ci++;\n"
"      }\n"
"      return {read: ci, written: encoded};\n"
"    };\n"
"  }\n"
"\n"
"  /* Install our TextDecoder as the global, replacing duktape's. */\n"
"  globalThis.TextDecoder = TextDecoder;\n"
"}";

void duk_rp_textencoding_init(duk_context *ctx)
{
    duk_push_string(ctx, "rampart-textencoding.c");
    duk_compile_string_filename(ctx, DUK_COMPILE_FUNCTION, _textencoding_js);
    duk_call(ctx, 0);
    duk_pop(ctx);   /* discard result */
}
