/* Copyright (C) 2026 Aaron Flin - All Rights Reserved
 * MIT license -- https://opensource.org/licenses/MIT
 *
 * rampart-console.c
 *
 * Adds node-style methods to the global `console`: time/timeEnd/timeLog,
 * table, group/groupEnd/groupCollapsed, count/countReset, clear.
 * Duktape's stock console only provides log/error/warn/info/debug/trace/
 * dir/assert; this fills the gap so any rampart code (not just nodeshim)
 * can use these idioms.
 */

#include "duktape.h"
#include "rampart.h"
#include "rampart-console.h"

static const char *_console_extras_js =
"function() {\n"
"  'use strict';\n"
"  var con = (typeof globalThis !== 'undefined' ? globalThis : this).console;\n"
"  if (!con) return;\n"
"\n"
"  /* Internal state, hidden via non-enumerable defineProperty. */\n"
"  var _timers   = {};\n"
"  var _counters = {};\n"
"  var _indent   = '';\n"
"\n"
"  function _now() {\n"
"    if (typeof performance !== 'undefined' && typeof performance.now === 'function')\n"
"      return performance.now();\n"
"    return Date.now();\n"
"  }\n"
"\n"
"  /* ----- time / timeEnd / timeLog ----- */\n"
"  function time(label) {\n"
"    label = (label === undefined) ? 'default' : String(label);\n"
"    if (_timers.hasOwnProperty(label)) {\n"
"      con.warn('Warning: Label \\'' + label + '\\' already exists for console.time()');\n"
"      return;\n"
"    }\n"
"    _timers[label] = _now();\n"
"  }\n"
"  function timeLog(label /*, ...extras */) {\n"
"    label = (label === undefined) ? 'default' : String(label);\n"
"    if (!_timers.hasOwnProperty(label)) {\n"
"      con.warn(\"Warning: No such label '\" + label + \"' for console.timeLog()\");\n"
"      return;\n"
"    }\n"
"    var elapsed = _now() - _timers[label];\n"
"    var msg = _indent + label + ': ' + elapsed.toFixed(3) + 'ms';\n"
"    var extras = Array.prototype.slice.call(arguments, 1);\n"
"    if (extras.length) con.log.apply(con, [msg].concat(extras));\n"
"    else con.log(msg);\n"
"  }\n"
"  function timeEnd(label) {\n"
"    label = (label === undefined) ? 'default' : String(label);\n"
"    if (!_timers.hasOwnProperty(label)) {\n"
"      con.warn(\"Warning: No such label '\" + label + \"' for console.timeEnd()\");\n"
"      return;\n"
"    }\n"
"    var elapsed = _now() - _timers[label];\n"
"    delete _timers[label];\n"
"    con.log(_indent + label + ': ' + elapsed.toFixed(3) + 'ms');\n"
"  }\n"
"\n"
"  /* ----- count / countReset ----- */\n"
"  function count(label) {\n"
"    label = (label === undefined) ? 'default' : String(label);\n"
"    _counters[label] = (_counters[label] || 0) + 1;\n"
"    con.log(_indent + label + ': ' + _counters[label]);\n"
"  }\n"
"  function countReset(label) {\n"
"    label = (label === undefined) ? 'default' : String(label);\n"
"    if (!_counters.hasOwnProperty(label)) {\n"
"      con.warn(\"Warning: Count for '\" + label + \"' does not exist\");\n"
"      return;\n"
"    }\n"
"    _counters[label] = 0;\n"
"  }\n"
"\n"
"  /* ----- group / groupEnd / groupCollapsed ----- */\n"
"  /* No tree-rendering UI -- just indent subsequent logs by 2 spaces. */\n"
"  function group(/* ...args */) {\n"
"    if (arguments.length) con.log.apply(con, arguments);\n"
"    _indent += '  ';\n"
"  }\n"
"  function groupEnd() {\n"
"    if (_indent.length >= 2) _indent = _indent.slice(0, -2);\n"
"  }\n"
"  /* groupCollapsed is identical to group in a non-DevTools environment. */\n"
"  var groupCollapsed = group;\n"
"\n"
"  /* ----- clear ----- */\n"
"  /* Emit ANSI clear-screen + cursor-home if stdout is a TTY-ish thing.\n"
"     Conservative: always emit; harmless in non-TTY contexts (just shows\n"
"     escape sequences in captured output, same as node). */\n"
"  function clear() {\n"
"    if (typeof process !== 'undefined' && process.stdout && process.stdout.isTTY === false) return;\n"
"    /* \\u001b[2J = erase entire display; \\u001b[H = move cursor to home */\n"
"    var out = '\\u001b[2J\\u001b[H';\n"
"    if (typeof process !== 'undefined' && process.stdout && typeof process.stdout.write === 'function')\n"
"      process.stdout.write(out);\n"
"    else\n"
"      con.log(out);\n"
"  }\n"
"\n"
"  /* ----- table ----- */\n"
"  /* Render an array of objects (or single object) as an ASCII table.\n"
"     `columns` is an optional whitelist of column names to include. */\n"
"  function _fmt(v) {\n"
"    if (v === null) return 'null';\n"
"    if (v === undefined) return '';\n"
"    if (typeof v === 'string') return v;\n"
"    if (typeof v === 'function') return '[Function]';\n"
"    try { return JSON.stringify(v); }\n"
"    catch (e) { return String(v); }\n"
"  }\n"
"  function table(data, columns) {\n"
"    if (data === null || typeof data !== 'object') { con.log(data); return; }\n"
"    var isArr = Array.isArray(data);\n"
"    var rows  = isArr ? data : Object.keys(data).map(function(k) { return data[k]; });\n"
"    var keys  = isArr ? [] : Object.keys(data);\n"
"    /* Collect column names */\n"
"    var cols = {};\n"
"    var firstKey = isArr ? '(index)' : '(index)';\n"
"    cols[firstKey] = true;\n"
"    rows.forEach(function(r) {\n"
"      if (r !== null && typeof r === 'object') {\n"
"        for (var k in r) if (Object.prototype.hasOwnProperty.call(r, k)) cols[k] = true;\n"
"      } else {\n"
"        cols['Values'] = true;\n"
"      }\n"
"    });\n"
"    if (columns && Array.isArray(columns)) {\n"
"      cols = {};\n"
"      cols[firstKey] = true;\n"
"      columns.forEach(function(c) { cols[c] = true; });\n"
"    }\n"
"    var colNames = Object.keys(cols);\n"
"    /* Build matrix */\n"
"    var matrix = [colNames];\n"
"    rows.forEach(function(r, i) {\n"
"      var row = [];\n"
"      var idxLabel = isArr ? String(i) : keys[i];\n"
"      colNames.forEach(function(c) {\n"
"        if (c === firstKey) row.push(idxLabel);\n"
"        else if (c === 'Values' && (r === null || typeof r !== 'object')) row.push(_fmt(r));\n"
"        else if (r !== null && typeof r === 'object') row.push(_fmt(r[c]));\n"
"        else row.push('');\n"
"      });\n"
"      matrix.push(row);\n"
"    });\n"
"    /* Column widths */\n"
"    var widths = colNames.map(function(_, c) {\n"
"      var w = 0;\n"
"      for (var i = 0; i < matrix.length; i++) {\n"
"        if (matrix[i][c].length > w) w = matrix[i][c].length;\n"
"      }\n"
"      return w;\n"
"    });\n"
"    /* Render */\n"
"    function pad(s, n) { while (s.length < n) s += ' '; return s; }\n"
"    function sep() {\n"
"      var s = '+';\n"
"      widths.forEach(function(w) { s += new Array(w + 3).join('-') + '+'; });\n"
"      return s;\n"
"    }\n"
"    function rowStr(r) {\n"
"      var s = '|';\n"
"      r.forEach(function(v, i) { s += ' ' + pad(v, widths[i]) + ' |'; });\n"
"      return s;\n"
"    }\n"
"    con.log(_indent + sep());\n"
"    con.log(_indent + rowStr(matrix[0]));\n"
"    con.log(_indent + sep());\n"
"    for (var i = 1; i < matrix.length; i++) con.log(_indent + rowStr(matrix[i]));\n"
"    con.log(_indent + sep());\n"
"  }\n"
"\n"
"  /* Attach (non-enumerable, writable, configurable). */\n"
"  function def(name, fn) {\n"
"    if (typeof con[name] === 'function') return; /* don't clobber if already there */\n"
"    Object.defineProperty(con, name, {\n"
"      value: fn, writable: true, enumerable: false, configurable: true\n"
"    });\n"
"  }\n"
"  def('time',            time);\n"
"  def('timeEnd',         timeEnd);\n"
"  def('timeLog',         timeLog);\n"
"  def('count',           count);\n"
"  def('countReset',      countReset);\n"
"  def('group',           group);\n"
"  def('groupEnd',        groupEnd);\n"
"  def('groupCollapsed',  groupCollapsed);\n"
"  def('clear',           clear);\n"
"  def('table',           table);\n"
"}";

void duk_rp_console_init(duk_context *ctx)
{
    duk_push_string(ctx, "rampart-console.c");
    duk_compile_string_filename(ctx, DUK_COMPILE_FUNCTION, _console_extras_js);
    duk_call(ctx, 0);
    duk_pop(ctx);  /* discard result */
}
