#ifndef DBCTRL_H
#define DBCTRL_H
/**********************************************************************/
#define TDB_VERSION      "db_version"
#define TDB_PRIM1        "db_prim1"
#define TDB_PRIM2        "db_prim2"
#define TDB_PRIM3        "db_prim3"
#define TDB_PRIM4        "db_prim4"
#define TDB_PRIM5        "db_prim5"
#define TDB_MAXTOKS      "db_maxtoks"
#define TDB_SEC0         "db_sec0"
#define TDB_SEC1         "db_sec1"
#define TDB_SEC2         "db_sec2"
#define TDB_SEC3         "db_sec3"
#define TDB_SEC4         "db_sec4"
#define TDB_SEC5         "db_sec5"
#define TDB_LOCK         "db_lock"
#define TDB_WHO          "db_who"
#define TDB_WORDDEF      "db_worddef"
#define TDB_BLOCKDELIM   "db_blockdelim"
#define TDB_BLOCKSZ      "db_blocksz"
#define TDB_BLOCKMAX     "db_blockmax"
#define TDB_ALLOW        "db_allow"
#define TDB_IGNORE       "db_ignore"
#define TDB_ADMINMSGS    "db_adminmsgs"
#define TDB_MAXSIMULT    "db_maxsimult"
#define TDB_PATHS        "db_paths"
#define TDB_DESCENDPATHS "db_descendpaths"
#define TDB_TIMESPEC     "db_timespec"
#define TDB_FILESPEC     "db_filespec"
#define TDB_ENABLEMM     "db_enablemm"
#define TDB_MAXSELECT    "db_maxselect"
#define TDB_BUFLEN       "db_buflen"
/**********************************************************************/
#endif                                                    /* DBCTRL_H */
