#ifndef MCTRL_H
#define MCTRL_H
/**********************************************************************/
/* 10-1-88 pbr : added MM_PPID, MM_SIGNAL , and MM_MSGFILE */
/* 6-9-89 pbr  : added query */
/* 8-29-90 maw : added filtername, highbitstrip */
/**********************************************************************/
#define MM_BACKREFCMD      "backrefcmd"
#define MM_BATCHMODE       "batchmode"
#define MM_COLORNORM       "color_norm"
#define MM_COLORBOLD       "color_bold"
#define MM_COLORREV        "color_rev"
#define MM_COLORFLASH      "color_flash"
#define MM_CTRLPREFIX      "ctrlprefix"
#define MM_DATABASE        "database"
#define MM_EDEXP           "edexp"
#define MM_EDIT_EQUIVS     "edit_equivs"
#define MM_ENGINECMD       "enginecmd"
#define MM_EQPREFIX        "eqprefix"
#define MM_UEQPREFIX       "ueqprefix"
#define MM_EQUIVS          "equivs"
#define MM_FILTER_MODE     "filter_mode"
#define MM_FILTERNAME      "filtername"
#define MM_HIDDEN_DIR      "hidden_dir"
#define MM_HIGHBITSTRIP    "highbitstrip"
#define MM_HOTFUNCTION     "hotfunction"
#define MM_HITFUNCTION     "hitfunction"
#define MM_INC_EDEXP       "inc_edexp"
#define MM_INC_SDEXP       "inc_sdexp"
#define MM_INDEX           "index"
#define MM_INTERSECTS      "intersects"
#define MM_ISASSOC         "isassoc"
#define MM_KEYS            "keys"
#define MM_MACROS          "macros"
#define MM_MDXDELIM        "indexdelim"
#define MM_MDXFILES        "indexfiles"
#define MM_MDXINFO         "indexinfo"
#define MM_MDXMSG          "indexmsg"
#define MM_MDXPATH         "indexpath"
#define MM_MDXPRINT        "indexprint"
#define MM_MESSAGE_TYPES   "message_types"
#define MM_MINDEXCMD       "mindexcmd"
#define MM_MINWORDLEN      "minwordlen"
#define MM_MSGPREFIX       "msgprefix"
#define MM_MULTIPASS       "multipass"
#define MM_CONCURRENT      "concurrent"
#define MM_USEEQUIV        "useequiv"
#define MM_NOISE           "noise"
#define MM_PIPEOUT         "pipeout"
#define MM_PPID            "ppid"
#define MM_PREFIX          "prefix"
#define MM_PREFIXPROC      "prefixproc"
#define MM_PRONOUN         "pronoun"
#define MM_QUERY           "query"
#define MM_QUESTION        "question"
#define MM_REBUILD         "rebuild"
#define MM_CONTEXT         "context"
#define MM_RECUR_DIR       "recur_dir"
#define MM_REPORTFILE      "reportfile"
#define MM_SDEXP           "sdexp"
#define MM_SEARCHFILES     "searchfiles"
#define MM_SEE_REFERENCE   "see_reference"
#define MM_SIGNAL          "signal"
#define MM_SUFFIX          "suffix"
#define MM_SUFFIXEQ        "suffixeq"
#define MM_SUFFIXPROC      "suffixproc"
#define MM_UIPOSTPROC      "uipostproc"
#define MM_WITHINPROC      "withinproc"
/**********************************************************************/
#endif                                                     /* MCTRL_H */

