void  *closemdbf ARGS((void *df));
void  *openmdbf  ARGS((char *fn, int mode));
int    freemdbf  ARGS((void *df, off_t at));
off_t  mdbfalloc ARGS((void *df,void *buf, size_t n));
off_t  putmdbf   ARGS((void *df, off_t at, void *buf, size_t sz));
void  *getmdbf   ARGS((void *df, off_t at, size_t *psz));
void  *agetmdbf  ARGS((void *df, off_t at, size_t *psz));
int    readmdbf  ARGS((void *df, off_t at, void *buf, size_t sz));
off_t  tellmdbf  ARGS((void *df));
char  *getmdbffn ARGS((void *df));
int    getmdbffh ARGS((void *df));
void   setmdbfoveralloc ARGS((void *df,int div));
int    validmdbf ARGS((void *df, off_t at));
void  *closemdbf3 ARGS((void *df));
void  *openmdbf3  ARGS((char *fn));
int    freemdbf3  ARGS((void *df, off_t at));
off_t  mdbf3alloc ARGS((void *df,void *buf, size_t n));
off_t  putmdbf3   ARGS((void *df, off_t at, void *buf, size_t sz));
void  *getmdbf3   ARGS((void *df, off_t at, size_t *psz));
void  *agetmdbf3  ARGS((void *df, off_t at, size_t *psz));
int    readmdbf3  ARGS((void *df, off_t at, void *buf, size_t sz));
off_t  tellmdbf3  ARGS((void *df));
char  *getmdbf3fn ARGS((void *df));
int    getmdbf3fh ARGS((void *df));
void   setmdbf3overalloc ARGS((void *df,int div));
int    validmdbf3 ARGS((void *df, off_t at));
