#!/bin/bash
# Helper script for building Python on Cygwin/MSYS.
# On Cygwin with --disable-shared, shared extension modules (.so) can't be
# built because the PE linker needs all symbols resolved at link time, and
# there's no shared libpython DLL to provide an import library.
# Fix: list needed modules in Setup.local as *static* so they get compiled
# directly into libpython3.x.a via the makesetup system.
set -e

PYTHON_MINOR="$1"
MAKE="$2"

# Create Modules/Setup.local to build extension modules statically.
# These modules would normally be built as shared (.so) by setup.py,
# but that fails on Cygwin without a shared libpython. By listing them
# in Setup.local with *static*, makesetup includes them in config.c
# and they get compiled into libpython3.x.a.
cat > Modules/Setup.local << 'SETUP_EOF'
# Cygwin static module configuration - generated by build_python_cygwin.sh
# All modules must be built statically because shared extension modules
# can't link without a shared libpython on Cygwin (PE format).
*static*

# Core modules
array arraymodule.c
_asyncio _asynciomodule.c
_bisect _bisectmodule.c
_contextvars _contextvarsmodule.c
_csv _csv.c
_heapq _heapqmodule.c
_json _json.c
_lsprof _lsprof.c rotatingtree.c
_opcode _opcode.c
_pickle _pickle.c
_queue _queuemodule.c
_random _randommodule.c
_struct _struct.c
_typing _typingmodule.c
_zoneinfo _zoneinfo.c

# Math modules (need -lm, linked by default on Cygwin)
audioop audioop.c
math mathmodule.c
cmath cmathmodule.c
_statistics _statisticsmodule.c
_datetime _datetimemodule.c

# _decimal with bundled libmpdec
_decimal _decimal/_decimal.c

# Compression and encoding
binascii binascii.c
zlib zlibmodule.c

# Hashing
_md5 md5module.c
_sha1 sha1module.c
_sha256 sha256module.c
_sha512 sha512module.c
_sha3 _sha3/sha3module.c
_blake2 _blake2/blake2module.c _blake2/blake2b_impl.c _blake2/blake2s_impl.c

# XML
pyexpat pyexpat.c
_elementtree _elementtree.c

# CJK codecs
_codecs_cn cjkcodecs/_codecs_cn.c
_codecs_hk cjkcodecs/_codecs_hk.c
_codecs_iso2022 cjkcodecs/_codecs_iso2022.c
_codecs_jp cjkcodecs/_codecs_jp.c
_codecs_kr cjkcodecs/_codecs_kr.c
_codecs_tw cjkcodecs/_codecs_tw.c
_multibytecodec cjkcodecs/multibytecodec.c
unicodedata unicodedata.c

# UNIX modules
fcntl fcntlmodule.c
grp grpmodule.c
mmap mmapmodule.c
_posixsubprocess _posixsubprocess.c
resource resource.c
select selectmodule.c
_socket socketmodule.c
syslog syslogmodule.c
termios termios.c

# Multiprocessing
_multiprocessing _multiprocessing/multiprocessing.c _multiprocessing/semaphore.c

# SQLite3
_sqlite3 _sqlite/blob.c _sqlite/connection.c _sqlite/cursor.c _sqlite/microprotocols.c _sqlite/module.c _sqlite/prepare_protocol.c _sqlite/row.c _sqlite/statement.c _sqlite/util.c -lsqlite3

# SSL/crypto (uses our bundled OpenSSL)
_ssl _ssl.c
_hashlib _hashopenssl.c
SETUP_EOF

echo "Created Modules/Setup.local with static module definitions"

# Build the static library and the python binary.
# makesetup will read Setup.local and generate config.c with all modules.
$MAKE -j4 "libpython3.${PYTHON_MINOR}.a" python

# Install - use -k to continue past failures (test shared modules will fail)
$MAKE -k install || true

# Verify the library was built
if [ ! -f "libpython3.${PYTHON_MINOR}.a" ]; then
    echo "ERROR: libpython3.${PYTHON_MINOR}.a was not built"
    exit 1
fi
